import CodeBlock from '../components/CodeBlock'
import { Note, Summary, Exercise, Emphbox } from '../components/Callouts'
import Figure from '../components/Figure'
import ChapterNav from '../components/ChapterNav'

export default function KeysAndAddresses() {
    return (
        <>
            <div className="chapter-header">
                <div className="chapter-number">Chapter 5</div>
                <h1>Keys and Addresses</h1>
            </div>

            <Summary>
                <p>
                    In this chapter we introduce Bitcoin's keys and addresses and describe how they are created
                    and the rationale behind that process. We then go through different wallet types and how
                    these keys can be used in practice.
                </p>
            </Summary>

            <h2 id="private-keys">Private Keys</h2>

            <p>
                Bitcoin uses the Elliptic Curve Digital Signature Algorithm (ECDSA) to create its
                private-public key pairs. The exact elliptic curve parameters used in Bitcoin are defined
                by <a href="https://en.bitcoin.it/wiki/Secp256k1" target="_blank" rel="noopener noreferrer">secp256k1</a>.
            </p>

            <Note>
                <p>
                    In ECDSA a private key can be used to calculate the corresponding public key, and since a
                    Bitcoin address is calculated from the public key, if you hold a private key securely you
                    effectively have everything.
                </p>
            </Note>

            <p>
                The ECDSA private key in Bitcoin is just a very large random number consisting of 256 bits
                or 32 bytes or 64 hexadecimal digits. To display a private key the most common format is
                Wallet Import Format (WIF) or WIF-compressed (WIFC); both are a Base58Check encoding of
                the ECDSA key.
            </p>

            <Emphbox>
                <pre>{`key_bytes = (32 bytes number) [ + 0x01 if compressed ]
network_prefix = (1 byte version number)
data = network_prefix + key_bytes
data_hash = SHA-256( SHA-256( data ) )
checksum = (first 4 bytes of data_hash)
wif = Base58CheckEncode( data + checksum )`}</pre>
            </Emphbox>

            <div className="table-wrapper">
                <table>
                    <thead>
                        <tr>
                            <th></th>
                            <th colSpan="2">Mainnet</th>
                            <th colSpan="2">Testnet</th>
                        </tr>
                        <tr>
                            <th></th>
                            <th>Network Prefix</th>
                            <th>Base58 Prefix</th>
                            <th>Network Prefix</th>
                            <th>Base58 Prefix</th>
                        </tr>
                    </thead>
                    <tbody>
                        <tr><td>WIF</td><td>128 | 0x80</td><td>5</td><td>239 | 0xef</td><td>9</td></tr>
                        <tr><td>WIF-C</td><td>128 | 0x80</td><td>K or L</td><td>239 | 0xef</td><td>c</td></tr>
                    </tbody>
                </table>
            </div>

            <p>Let's use the bitcoin-utils library to construct the WIF and WIFC:</p>

            <CodeBlock language="python" caption="Example of creating WIF and WIFC using Python" code={`>>> from bitcoinutils.setup import setup
>>> from bitcoinutils.keys import PrivateKey
>>> setup('testnet')
'testnet'
>>> secret_exponent = 0x0dde70823a4bb0ca3bd75a2010e8d5dc091185e73d8b4257a981c695a3eba95b
>>> priv = PrivateKey(secret_exponent = secret_exponent)
>>> priv.to_wif(compressed=False)
'91h2ReUJRwJhTNd828zhc8RRVMU4krX9q3LNi4nVfiVwkMPfA9p'
>>> priv.to_wif(compressed=True)                       # the default
'cN3fHnPVw4h7ZQSRz2HgE3ko69LTaZa5y3JWpFhoXtAke4MiqVQo'`} />

            <h2 id="public-keys">Public Keys</h2>

            <p>
                The public key P is generated by multiplying the private key k with a special constant G
                called the generator point: P = k × G. The specific curve Bitcoin uses (secp256k1)
                is y² = x³ + 7.
            </p>

            <Figure
                src="./images/ecdsa-curve.png"
                caption="The secp256k1 ECDSA curve."
                label="fig-ecdsa-curve"
            />

            <Note>
                <p>
                    We can represent a public key in two forms, compressed and uncompressed. Using the
                    compressed form reduces the size of the blockchain.
                </p>
            </Note>

            <p>
                An encoded uncompressed public key is 65 bytes (prefix <code>0x04</code> + x + y).
                A compressed public key is only 33 bytes (prefix <code>0x02</code> or <code>0x03</code> + x only).
            </p>

            <CodeBlock language="python" caption="Python example to generate compressed and uncompressed public keys" code={`>>> from bitcoinutils.setup import setup
>>> from bitcoinutils.keys import PrivateKey, PublicKey
>>> setup('testnet')
'testnet'
>>> priv = PrivateKey.from_wif('91h2ReUJRwJhTNd828zhc8RRVMU4krX9q3LNi4nVfiVwkMPfA9p')
>>> pub = priv.get_public_key()
>>> pub.to_hex()                # default is compressed form
'02c1acdac799fb0308b4b6475ddf7967676759d31484ab55555482472f3bc7c3e7'
>>> pub.to_hex(compressed=False)
'04c1acdac799fb0308b4b6475ddf7967676759d31484ab55555482472f3bc7c3e7\\
addc4cbba6656a4be4bc6933a6af712b897a543a09c4b899e5f7b943d38108a8'`} />

            <h2 id="addresses">Addresses</h2>

            <p>
                Addresses can be shared to anyone who wants to send you money. They are typically generated
                from the public key. An address typically represents the owner of a private/public pair but
                it can also represent a more complex script.
            </p>

            <h3>Legacy Addresses</h3>

            <p>
                An address is really just the hash of the public key, called public key hash (or PKH).
                The format we use is the Base58Check encoding of the public key hash.
            </p>

            <Emphbox>
                <pre>{`network_prefix = (1 byte version number)
keyHash = RIPEMD-160( SHA-256( publicKey ) )
data = network_prefix + keyHash
dataHash = SHA-256( SHA-256( data ) )
checksum = (first 4 bytes of dataHash)
address = Base58CheckEncode( data + checksum )`}</pre>
            </Emphbox>

            <div className="table-wrapper">
                <table>
                    <thead>
                        <tr>
                            <th></th>
                            <th colSpan="2">Mainnet</th>
                            <th colSpan="2">Testnet</th>
                        </tr>
                        <tr>
                            <th></th>
                            <th>Network Prefix</th>
                            <th>Base58 Prefix</th>
                            <th>Network Prefix</th>
                            <th>Base58 Prefix</th>
                        </tr>
                    </thead>
                    <tbody>
                        <tr><td>P2PKH</td><td>0 | 0x00</td><td>1</td><td>111 | 0x6f</td><td>m or n</td></tr>
                        <tr><td>P2SH</td><td>5 | 0x05</td><td>3</td><td>196 | 0xc4</td><td>2</td></tr>
                    </tbody>
                </table>
            </div>

            <CodeBlock language="python" caption="Python example to generate compressed and uncompressed addresses" code={`>>> from bitcoinutils.setup import setup
>>> from bitcoinutils.keys import PrivateKey, PublicKey, P2pkhAddress
>>> setup('testnet')
'testnet'
>>> priv = PrivateKey.from_wif('91h2ReUJRwJhTNd828zhc8RRVMU4krX9q3LNi4nVfiVwkMPfA9p')
>>> pub = priv.get_public_key()
>>> addr1 = pub.get_address()
>>> addr2 = pub.get_address(compressed=False)
>>> addr1.to_string()
'n42m3hGC52QTChUbXq3QAPVU6nWkG9xuWj'
>>> addr2.to_string()
'n2JjAgC6UqFf8DvsZXhWcyNzm8w8YKj7MQ'`} />

            <Note>
                <p>
                    Since the hash of a compressed public key would be different from the hash of an
                    uncompressed public key we have two distinct legacy addresses.
                </p>
            </Note>

            <h3>Native Segregated Witness Addresses</h3>

            <p>
                Native segwit addresses use Bech32 encoding. Mainnet addresses start with <code>bc1</code>,
                testnet with <code>tb1</code> and regtest with <code>bcrt1</code>.
            </p>

            <CodeBlock language="python" caption="Example of displaying a segwit address from a public key using Python" code={`>>> from bitcoinutils.setup import setup
>>> from bitcoinutils.keys import PrivateKey, PublicKey, P2wpkhAddress
>>> setup('testnet')
'testnet'
>>> priv = PrivateKey.from_wif('91h2ReUJRwJhTNd828zhc8RRVMU4krX9q3LNi4nVfiVwkMPfA9p')
>>> pub = priv.get_public_key()
>>> addr = pub.get_segwit_address()
>>> addr.to_string()
'tb1q7m6ak6k050sxzxjjekhey73k0f3rqnxsqa08k2'`} />

            <h3>Vanity Addresses</h3>

            <p>
                These are normal addresses that contain a specific string. They are calculated by creating
                random private keys and checking if the corresponding address starts with a desired string.
            </p>

            <CodeBlock language="python" caption="Example of creating a vanity address using Python" code={`import random
from bitcoinutils.setup import setup
from bitcoinutils.keys import PrivateKey

setup('mainnet')

vanity_string = '1KK'
found = False
attempts = 0

while(not found):
    p = PrivateKey(secret_exponent = random.getrandbits(256))
    a = p.get_public_key().get_address()
    attempts += 1
    if(a.to_string().startswith(vanity_string)):
        found = True

print("Attempts: {}".format(attempts))
print("Address: {}".format(a.to_string()))
print("Secret Key: {}".format(p.to_wif()))`} />

            <p>
                Since addresses use base58, each character will take an average of 58 attempts.
                Generalizing: 58<sup>n</sup> where n is the number of vanity characters.
            </p>

            <h4>Vanity Address Pools</h4>

            <p>
                Vanity address pools take advantage of a property where the public key of the sum of two
                public keys corresponds to the private key of the sum of the corresponding private keys.
            </p>

            <Figure
                src="./images/vanity-address-pools.png"
                caption="Example of how a vanity address pool securely shares the private key to a user."
                label="fig-vanity-address-pools"
            />

            <h2 id="wallets">Wallets</h2>

            <p>
                A wallet is software that allows us to manage private and public keys as well as Bitcoin
                addresses. There are two types:
            </p>

            <dl>
                <dt>Non-deterministic</dt>
                <dd>All private keys are randomly generated. If you create new keys you need a new backup.</dd>
                <dt>Deterministic</dt>
                <dd>A seed creates a master private key, which generates all other keys. Backup the seed once.</dd>
            </dl>

            <p>
                Nowadays, most wallets are <em>Hierarchical Deterministic (HD)</em> as described in BIPs 32,
                43, and 44.
            </p>

            <h2 id="more-examples">More Examples</h2>

            <h3>Create a P2SH-P2WPKH address</h3>

            <CodeBlock language="python" code={`>>> from bitcoinutils.setup import setup
>>> from bitcoinutils.keys import PrivateKey, P2shAddress
>>> setup('testnet')
'testnet'
>>> native_p2wpkh = PrivateKey.from_wif('cTmyBsxMQ3vyh4J3jCKYn2A'\\
...         'u7AhTKvqeYuxxkinsg6Rz3BBPrYKK').get_public_key().get_segwit_address()
>>> print("P2WPKH:", native_p2wpkh.to_string())
P2WPKH: tb1qsd4ax84vhem5hxgxus2u232nw9ylgftkz0szf2
>>> nested_p2wpkh = P2shAddress.from_script(native_p2wpkh.to_script_pub_key())
>>> print("P2SH(P2WPKH):", nested_p2wpkh.to_string())
P2SH(P2WPKH): 2N8Z5t3GyPW1hSAEJZqQ1GUkZ9ofoGhgKPf`} />

            <h3>Sign message with private key and verify</h3>

            <CodeBlock language="python" caption="Use public key to sign a message and then verify" code={`>>> from bitcoinutils.setup import setup
>>> from bitcoinutils.keys import P2pkhAddress, PrivateKey, PublicKey
>>> setup('testnet')
'testnet'
>>> priv = PrivateKey.from_wif('91h2ReUJRwJhTNd828zhc8RRVMU4krX9q3LNi4nVfiVwkMPfA9p')
>>> address = priv.get_public_key().get_address()
>>> message = "The test!"
>>> signature = priv.sign_message(message)
>>> print("The signature is:", signature)
The signature is: INzSwXNYNUkPFImslSFDzvqoib3ZdODcaBSZHvx5e4z1wc64cF1dVMZbDFtZxYBlD\\
L/dsjK2iBD5qAf7VcmSdQo=
>>> if PublicKey.verify_message(address.to_string(), signature, message):
...     print("The signature is valid!")
The signature is valid!`} />

            <Note>
                <p>
                    We verify using the address instead of the public key. In ECDSA cryptography the public key
                    can be reconstructed given the signature and the public key hash (or address).
                </p>
            </Note>

            <h2 id="exercises">Exercises</h2>

            <Exercise number={1}>
                <p>Describe possible outcomes of mistyping a Bitcoin address when trying to send some bitcoins.</p>
            </Exercise>
            <Exercise number={2}>
                <p>Use a vanity generator to create some addresses.</p>
            </Exercise>
            <Exercise number={3}>
                <p>Use Python and the <code>bitcoin-utils</code> library to create a simple vanity generator.</p>
            </Exercise>
            <Exercise number={4}>
                <p>Write a function that creates a Bitcoin address given a public key. Only use <code>hashlib</code> and <code>binascii</code>.</p>
            </Exercise>
            <Exercise number={5}>
                <p>Create and display a P2SH address that contains a P2PK script using any random private key.</p>
            </Exercise>

            <ChapterNav
                prev={{ path: '/technical-fundamentals', title: 'Technical Fundamentals' }}
                next={{ path: '/scripting-1', title: 'Scripting 1' }}
            />
        </>
    )
}
